'use client';

import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/packages/ui/Header';
import Navbar from '@/packages/ui/Navbar';
import Footer from '@/packages/ui/Footer';
import { useState } from 'react';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [overflow, setOverflow] = useState('auto');

  return (
    <html lang="en">
      <body
        style={{ overflow: overflow }}
        className={' h-screen w-full flex flex-col'}>
        <Header />
        <Navbar setOverflow={setOverflow} />
        <div className="grow w-full max-w-[1800px] mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
