import './globals.css';
import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import { Poppins } from 'next/font/google';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import Header from '@/packages/ui/common/Header';
import Navbar from '@/packages/ui/navbar/Navbar';
import Footer from '@/packages/ui/common/Footer';
// import { cookies } from 'next/headers';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Linus Tech Tips Store',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const theme = cookies().get('theme')?.value;

  return (
    <html
      lang="en"
      // data-theme={theme === 'dark' ? 'dark' : 'light'}
    >
      <body
        className={
          'min-h-screen w-full flex flex-col overflow-y-scroll ' +
          poppins.className
        }>
        <Header />
        <Navbar />
        <div className="grow w-full max-w-[1800px] mx-auto">{children}</div>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
